package semo.back.service.support;

import semo.back.service.database.pub.entity.DashboardWidgetCatalog;
import semo.back.service.database.pub.entity.FeatureCatalog;
import semo.back.service.database.pub.repository.DashboardWidgetCatalogRepository;
import semo.back.service.database.pub.repository.FeatureCatalogRepository;

import java.util.List;

public final class TestCatalogSeeder {
    private TestCatalogSeeder() {
    }

    public static void seedFeatureCatalogs(FeatureCatalogRepository featureCatalogRepository) {
        featureCatalogRepository.deleteAll();
        featureCatalogRepository.saveAll(List.of(
                FeatureCatalog.builder()
                        .featureKey("JOIN_REQUEST")
                        .displayName("가입 신청")
                        .description("관리자가 가입 신청 대기열을 검토하고 승인 또는 반려합니다.")
                        .iconName("group_add")
                        .navigationScope("ADMIN_ONLY")
                        .active(true)
                        .sortOrder(10)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("ATTENDANCE")
                        .displayName("일정 참석")
                        .description("대표 캘린더의 일정별 참가 응답과 참석 현황을 관리합니다.")
                        .iconName("fact_check")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(45)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("TIMELINE")
                        .displayName("내 활동")
                        .description("멤버는 자신의 활동을 확인하고 운영진은 감사 로그에서 전체 활동을 조회합니다.")
                        .iconName("timeline")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(110)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("NOTICE")
                        .displayName("게시판 공지")
                        .description("대표 게시판에서 공지를 작성하고 공유 범위를 관리합니다.")
                        .iconName("campaign")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(20)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("POLL")
                        .displayName("투표")
                        .description("대표 캘린더에서 투표를 작성하고 응답 결과를 관리합니다.")
                        .iconName("poll")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(40)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("SCHEDULE_MANAGE")
                        .displayName("일정")
                        .description("대표 캘린더에서 일정을 작성하고 참가 응답을 관리합니다.")
                        .iconName("edit_calendar")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(30)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("TOURNAMENT_RECORD")
                        .displayName("대회 운영")
                        .description("대회 등록, 승인, 참가 신청과 참가자 확정을 한 흐름에서 운영합니다.")
                        .iconName("emoji_events")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(50)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("BRACKET")
                        .displayName("대진표 초안")
                        .description("대회 참가자를 불러와 표준 시드 배치 초안을 만들고 관리자 승인을 받습니다.")
                        .iconName("account_tree")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(51)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("FINANCE")
                        .displayName("회비·정산")
                        .description("회비 수납, 멤버 요청, 승인 지출과 지출 원장을 분리해 관리합니다.")
                        .iconName("payments")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(60)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("MEMBER_DIRECTORY")
                        .displayName("멤버·조직")
                        .description("멤버가 공개한 프로필과 직책을 조회하며 최근 활동은 기본 비공개로 보호합니다.")
                        .iconName("group_search")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(80)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("FEEDBACK")
                        .displayName("피드백")
                        .description("비공개로 건의와 불편 신고를 접수하고 운영 답변을 확인합니다.")
                        .iconName("forum")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(90)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("TODO")
                        .displayName("할 일")
                        .description("담당자와 지원 가능 업무를 명확하게 관리하고 완료 상태를 추적합니다.")
                        .iconName("assignment")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(70)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("ROLE_MANAGEMENT")
                        .displayName("직책관리")
                        .description("직책을 생성하고 하위 권한을 연결해 멤버 권한을 세밀하게 관리합니다.")
                        .iconName("manage_accounts")
                        .navigationScope("ADMIN_ONLY")
                        .active(true)
                        .sortOrder(100)
                        .build()
        ));
    }

    public static void seedDashboardWidgetCatalogs(DashboardWidgetCatalogRepository dashboardWidgetCatalogRepository) {
        dashboardWidgetCatalogRepository.deleteAll();
        dashboardWidgetCatalogRepository.saveAll(List.of(
                DashboardWidgetCatalog.builder()
                        .widgetKey("BOARD_NOTICE")
                        .displayName("Board Notice")
                        .description("Latest announcements from your board.")
                        .iconName("forum")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(2)
                        .defaultRowSpan(1)
                        .defaultSortOrder(10)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("BOARD_STRIP")
                        .displayName("Board Strip")
                        .description("Compact strip of the latest board notices.")
                        .iconName("vertical_distribute")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(2)
                        .defaultSortOrder(12)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("SCHEDULE_OVERVIEW")
                        .displayName("Schedule Overview")
                        .description("Upcoming schedules and next events.")
                        .iconName("calendar_month")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(20)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("SCHEDULE_INSIGHT")
                        .displayName("Schedule Insight")
                        .description("Upcoming and pending schedule metrics.")
                        .iconName("schedule")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(22)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("POLL_STATUS")
                        .displayName("Poll Status")
                        .description("Latest ongoing poll for your club.")
                        .iconName("poll")
                        .requiredFeatureKey("POLL")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(25)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("POLL_PULSE")
                        .displayName("Poll Pulse")
                        .description("Waiting, ongoing, and closed poll counts.")
                        .iconName("stacked_bar_chart")
                        .requiredFeatureKey("POLL")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(27)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("TOURNAMENT_RECORD_LATEST")
                        .displayName("Tournament Center")
                        .description("Featured tournament and my closest tournament.")
                        .iconName("emoji_events")
                        .requiredFeatureKey("TOURNAMENT_RECORD")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(2)
                        .defaultRowSpan(1)
                        .defaultSortOrder(35)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("TOURNAMENT_RECORD_MINE")
                        .displayName("My Tournaments")
                        .description("My tournament pipeline and participation counts.")
                        .iconName("sports_score")
                        .requiredFeatureKey("TOURNAMENT_RECORD")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(36)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("BRACKET_LATEST")
                        .displayName("Bracket Board")
                        .description("Approved brackets and my latest draft.")
                        .iconName("account_tree")
                        .requiredFeatureKey("BRACKET")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(37)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("BRACKET_WORKBENCH")
                        .displayName("Bracket Workbench")
                        .description("Approved, pending, and my bracket counts.")
                        .iconName("view_timeline")
                        .requiredFeatureKey("BRACKET")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(37)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("PROFILE_SUMMARY")
                        .displayName("My Profile")
                        .description("Quick access to your club profile.")
                        .iconName("person")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(30)
                        .active(true)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("ATTENDANCE_STATUS")
                        .displayName("Attendance Check")
                        .description("Check in and review attendance status.")
                        .iconName("fact_check")
                        .requiredFeatureKey("ATTENDANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(40)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("ATTENDANCE_RECENT")
                        .displayName("Attendance Recent")
                        .description("Recent attendance logs and completion rate.")
                        .iconName("event_note")
                        .requiredFeatureKey("ATTENDANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(41)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("FINANCE_STATUS")
                        .displayName("Finance Status")
                        .description("My pending finance items and latest payment status.")
                        .iconName("payments")
                        .requiredFeatureKey("FINANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(42)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("FINANCE_LEDGER")
                        .displayName("Finance Ledger")
                        .description("Pending and completed finance summary.")
                        .iconName("account_balance_wallet")
                        .requiredFeatureKey("FINANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(44)
                        .active(true)
                        .build()
        ));
    }
}
