package semo.back.service.support;

import semo.back.service.database.pub.entity.DashboardWidgetCatalog;
import semo.back.service.database.pub.entity.FeatureCatalog;
import semo.back.service.database.pub.repository.DashboardWidgetCatalogRepository;
import semo.back.service.database.pub.repository.FeatureCatalogRepository;

import java.util.List;

public final class TestCatalogSeeder {
    private TestCatalogSeeder() {
    }

    public static void seedFeatureCatalogs(FeatureCatalogRepository featureCatalogRepository) {
        featureCatalogRepository.deleteAll();
        featureCatalogRepository.saveAll(List.of(
                FeatureCatalog.builder()
                        .featureKey("ATTENDANCE")
                        .displayName("출석 체크")
                        .description("멤버 출석을 체크하고 출석 세션을 관리합니다.")
                        .iconName("fact_check")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(10)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("TIMELINE")
                        .displayName("타임라인")
                        .description("모임 전체 활동을 시간순 타임라인으로 확인합니다.")
                        .iconName("timeline")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(20)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("NOTICE")
                        .displayName("공지관리")
                        .description("공지 콘텐츠를 작성하고 게시판/캘린더에 공유합니다.")
                        .iconName("campaign")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(30)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("POLL")
                        .displayName("투표")
                        .description("모임 투표를 작성, 공유, 관리합니다.")
                        .iconName("poll")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(40)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("SCHEDULE_MANAGE")
                        .displayName("일정관리")
                        .description("일정 콘텐츠를 작성하고 게시판/캘린더에 공유합니다.")
                        .iconName("edit_calendar")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(50)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("TOURNAMENT_RECORD")
                        .displayName("대회기록")
                        .description("대회를 작성하고 관리자 승인 이후 참가신청과 참가 선수를 운영합니다.")
                        .iconName("emoji_events")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(55)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("BRACKET")
                        .displayName("대진표")
                        .description("직접 작성하거나 대회 참가자를 불러와 대진표 초안을 만들고 관리자 승인을 받습니다.")
                        .iconName("account_tree")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(57)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("FINANCE")
                        .displayName("재정관리")
                        .description("멤버별 재정 항목을 발행하고 납부 상태를 운영합니다.")
                        .iconName("payments")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(58)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("MEMBER_DIRECTORY")
                        .displayName("회원 디렉터리")
                        .description("다른 회원의 직책, 한줄소개, 최근 활동을 한 화면에서 조회합니다.")
                        .iconName("group_search")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(59)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("FEEDBACK")
                        .displayName("피드백")
                        .description("익명 또는 기명으로 건의, 불편 신고, 개선 요청을 남기고 운영 답변을 확인합니다.")
                        .iconName("forum")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(59)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("TODO")
                        .displayName("할 일")
                        .description("담당자와 지원 가능 업무를 명확하게 관리하고 완료 상태를 추적합니다.")
                        .iconName("assignment")
                        .navigationScope("USER_AND_ADMIN")
                        .active(true)
                        .sortOrder(59)
                        .build(),
                FeatureCatalog.builder()
                        .featureKey("ROLE_MANAGEMENT")
                        .displayName("직책관리")
                        .description("직책을 생성하고 하위 권한을 연결해 멤버 권한을 세밀하게 관리합니다.")
                        .iconName("manage_accounts")
                        .navigationScope("ADMIN_ONLY")
                        .active(true)
                        .sortOrder(60)
                        .build()
        ));
    }

    public static void seedDashboardWidgetCatalogs(DashboardWidgetCatalogRepository dashboardWidgetCatalogRepository) {
        dashboardWidgetCatalogRepository.deleteAll();
        dashboardWidgetCatalogRepository.saveAll(List.of(
                DashboardWidgetCatalog.builder()
                        .widgetKey("BOARD_NOTICE")
                        .displayName("Board Notice")
                        .description("Latest announcements from your board.")
                        .iconName("forum")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(2)
                        .defaultRowSpan(1)
                        .defaultSortOrder(10)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("BOARD_STRIP")
                        .displayName("Board Strip")
                        .description("Compact strip of the latest board notices.")
                        .iconName("vertical_distribute")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(2)
                        .defaultSortOrder(12)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("SCHEDULE_OVERVIEW")
                        .displayName("Schedule Overview")
                        .description("Upcoming schedules and next events.")
                        .iconName("calendar_month")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(20)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("SCHEDULE_INSIGHT")
                        .displayName("Schedule Insight")
                        .description("Upcoming and pending schedule metrics.")
                        .iconName("schedule")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(22)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("POLL_STATUS")
                        .displayName("Poll Status")
                        .description("Latest ongoing poll for your club.")
                        .iconName("poll")
                        .requiredFeatureKey("POLL")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(25)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("POLL_PULSE")
                        .displayName("Poll Pulse")
                        .description("Waiting, ongoing, and closed poll counts.")
                        .iconName("stacked_bar_chart")
                        .requiredFeatureKey("POLL")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(27)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("TOURNAMENT_RECORD_LATEST")
                        .displayName("Tournament Center")
                        .description("Featured tournament and my closest tournament.")
                        .iconName("emoji_events")
                        .requiredFeatureKey("TOURNAMENT_RECORD")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(2)
                        .defaultRowSpan(1)
                        .defaultSortOrder(35)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("TOURNAMENT_RECORD_MINE")
                        .displayName("My Tournaments")
                        .description("My tournament pipeline and participation counts.")
                        .iconName("sports_score")
                        .requiredFeatureKey("TOURNAMENT_RECORD")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(36)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("BRACKET_LATEST")
                        .displayName("Bracket Board")
                        .description("Approved brackets and my latest draft.")
                        .iconName("account_tree")
                        .requiredFeatureKey("BRACKET")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(37)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("BRACKET_WORKBENCH")
                        .displayName("Bracket Workbench")
                        .description("Approved, pending, and my bracket counts.")
                        .iconName("view_timeline")
                        .requiredFeatureKey("BRACKET")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(37)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("PROFILE_SUMMARY")
                        .displayName("My Profile")
                        .description("Quick access to your club profile.")
                        .iconName("person")
                        .requiredFeatureKey(null)
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(30)
                        .active(true)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("ATTENDANCE_STATUS")
                        .displayName("Attendance Check")
                        .description("Check in and review attendance status.")
                        .iconName("fact_check")
                        .requiredFeatureKey("ATTENDANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(40)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("ATTENDANCE_RECENT")
                        .displayName("Attendance Recent")
                        .description("Recent attendance logs and completion rate.")
                        .iconName("event_note")
                        .requiredFeatureKey("ATTENDANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(41)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("FINANCE_STATUS")
                        .displayName("Finance Status")
                        .description("My pending finance items and latest payment status.")
                        .iconName("payments")
                        .requiredFeatureKey("FINANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(42)
                        .active(true)
                        .build(),
                DashboardWidgetCatalog.builder()
                        .widgetKey("FINANCE_LEDGER")
                        .displayName("Finance Ledger")
                        .description("Pending and completed finance summary.")
                        .iconName("account_balance_wallet")
                        .requiredFeatureKey("FINANCE")
                        .defaultVisibilityScope("USER_HOME")
                        .defaultColumnSpan(1)
                        .defaultRowSpan(1)
                        .defaultSortOrder(44)
                        .active(true)
                        .build()
        ));
    }
}
