package semo.back.service.feature.todo.vo;

import java.util.List;

public record TodoSummaryResponse(
        Long todoItemId,
        String title,
        String description,
        String todoType,
        String todoTypeLabel,
        String assignmentMode,
        String assignmentModeLabel,
        String statusCode,
        String statusLabel,
        String priorityCode,
        String priorityLabel,
        String dueAt,
        String dueAtLabel,
        String workStartAt,
        String workEndAt,
        String workTimeLabel,
        boolean overdue,
        Long assignedClubProfileId,
        String assignedDisplayName,
        List<TodoAssigneeResponse> assignees,
        int assigneeCount,
        int recruitmentCapacity,
        boolean recruitmentFull,
        Long linkedScheduleEventId,
        String linkedScheduleTitle,
        String createdByDisplayName,
        String completedByDisplayName,
        String completedAt,
        String completedAtLabel,
        boolean canClaim,
        boolean canApply,
        boolean canCancelApplication,
        boolean canComplete,
        boolean canEdit,
        boolean canManageStatus,
        boolean canReviewApplications,
        Long myApplicationId,
        String myApplicationStatus,
        String myApplicationStatusLabel,
        int applicationCount
) {
}
